title: Mahi'Log
name: "Mahi's Tech Blog"
author: Mahi Rahimi
twitter_username: mahirahimi
baseurl: "/mahi-log"
description: Document my learning notes.
profile_url: "http://mahi97.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
excerpt_separator: <!--more-->
plugins:
  - jekyll-feed
  - jekyll-archives
exclude:
  - Gemfile
  - Gemfile.lock
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

collections:
  logs:
    output: true
